### ISSUE TITLE
Xamarin.iOS subscription does not receive events

### ISSUE THREAD

**Issue by grokify** [ringcentral/ringcentral-csharp#28]
In version [`0.1.21` (PubNubPCL release)](https://www.nuget.org/packages/RingCentralSDK/0.1.21) and the current `master` and `1.0.0` branches, events are not received by Xamarin.iOS but are received by Xamarin.Android and Xamarin.Mac. In the previously released version, [`0.1.1`](https://www.nuget.org/packages/RingCentralSDK/0.1.1), events are received by all 3. This was tested with `message-store` and `presence` events using Xamarin Studio Community 5.10.3 (build 51) and iOS Simulator 9.2.

This looks like it may be a continuation of issue #20.

**Comment by tylerlong** [comment]
This is weird because both RingCentral SDK and PubNub SDK are PCL(Portable Class Library) Projects. The code should work across platforms.

I am going to write some unit tests about subscription and run it against real API servers on different platforms including iOS.

**Comment by tylerlong** [comment]
I run this unit test using Xamarin Studio on Mac: https://github.com/ringcentral/ringcentral-csharp/blob/1.0.0/RingCentral.Test.Real/SubscriptionTest.cs  And the test passed without issue.

I am going to write a demo iOS project to test it manually.

**Comment by tylerlong** [comment]
@grokify 

I cannot reproduce the issue. Here is the demo code: https://github.com/tylerlong/RC.Xamarin.iOS.Subscription.Demo

```csharp
var sdk = new SDK (Config.AppKey, Config.AppSecret, Config.Server, "Test App", "1.0.0");
var platform = sdk.GetPlatform ();
platform.Authorize (Config.Username, Config.Extension, Config.Password, false);

var sub = new SubscriptionServiceImplementation() { _platform = platform };
sub.AddEvent("/restapi/v1.0/account/~/extension/~/message-store");
sub.Subscribe((message) => {
	Console.WriteLine("Event Received");
}, null, null);

var dict = new Dictionary<string, dynamic> {
	{ "text", "hello world" },
	{ "from", new Dictionary<string, string> { { "phoneNumber", Config.Username} } },
	{ "to", new Dictionary<string, string>[] { new Dictionary<string, string> { { "phoneNumber", Config.Receiver } } } },
};
var request = new Request("/restapi/v1.0/account/~/extension/~/sms", JsonConvert.SerializeObject(dict));
for(var i=0; i < 10; i++)
{
	platform.Post(request);
	Thread.Sleep (30000);
}
sub.Remove();
```

I could see that `"Event Received"` was printed 10 times which proves that events has been received.

Could you please share your source code with me?

**Comment by grokify** [comment]
@tylerlong 

Here's my code for iOS. Similar code in the same directory works for Mac and Android.

https://github.com/grokify/ringcentral-sdk-csharp-simple/blob/master/docs/sample_code/xamarin.ios.Main.cs

**Comment by tylerlong** [comment]
Something funny happened! The unit test code I posted above doesn't work any more: https://github.com/ringcentral/ringcentral-csharp/blob/1.0.0/RingCentral.Test.Real/SubscriptionTest.cs

Nothing was changed since last time I successfully run it (for a couple of times). So I think it is a bug from the server side. The unit test fails on all platforms (Windows, Mac...etc)

**Comment by tylerlong** [comment]
@grokify  for your sample code, I could make it working by simply removing a line of code:

```csharp
subscription.AddEvent("/restapi/v1.0/account/~/extension/~/presence");
```

I haven't found the root cause but at least I have got some clue.

**Comment by tylerlong** [comment]
It turns out the the issue I had on Windows is not the same issue on iOS. Because I have now fixed the Windows issue, but I still cannot get it working on iOS.

The issue for Windows is a rather silly one: I need to Reference PCLCrypto. Without PCLCrypto, the compiler doesn't complain but it just doesn't work.

**Comment by tylerlong** [comment]
I can reproduce the issue on Android.

works:
```
// sub.AddEvent("/restapi/v1.0/account/~/extension/~/presence");
sub.AddEvent("/restapi/v1.0/account/~/extension/~/message-store");
```

doesn't work:

```
sub.AddEvent("/restapi/v1.0/account/~/extension/~/presence");
sub.AddEvent("/restapi/v1.0/account/~/extension/~/message-store");
```

**Comment by grokify** [comment]
> @changbenny helped to test with his JS widget and he confirmed that subscription doesn't work with sandbox environment. So we can conclude that this issue has nothing to do with C# SDK. The root cause is sandbox server. So, shall we involve developers from the platform team?
>
> He also confirmed that the messages were sent successfully (but no events from subscription) so this is not an out-of-credits issue.

This sounds like a bug with the JS widget. The [CTI Demo app](https://github.com/ringcentral/ringcentral-cti-demo-js) will subscribe for and process incoming events from the sandbox. See [`ctiscreenpop.js` line 84 ](https://github.com/ringcentral/ringcentral-cti-demo-js/blob/master/public/js/ctiscreenpop.js#L84).

**Comment by tylerlong** [comment]
I have got it working with iOS, finally!

![screen shot 2016-05-25 at 12 40 11 pm](https://cloud.githubusercontent.com/assets/733544/15528415/5db2b032-2276-11e6-9003-c2a6bfa7eeee.png)

I will post more detail later.

**Comment by tylerlong** [comment]
##### Root cause:

[PCLCrypto](https://www.nuget.org/packages/PCLCrypto) doesn't work for iOS. It should work, but I tried so many times and failed to make it working. There was no compiler errors, no runtime errors and no events from pubnub(unfortunately).

##### Solution:

I replaced [PCLCrypto](https://www.nuget.org/packages/PCLCrypto) with [Portable.BouncyCastle](https://www.nuget.org/packages/Portable.BouncyCastle/) and rewrote the decryption method: https://github.com/ringcentral/ringcentral-csharp/commit/8e9770b9935e14324003b1bad53882080deb6288

By the way, Portable.BouncyCastle's NuGet page doesn't say that it supports ECB cipher mode. I figured it out by read [its test case](https://github.com/onovotny/BouncyCastle-PCL/blob/b7e5032ad477410b05df569ea742f82cd04246a1/crypto/test/src/test/AESTest.cs).

**Comment by grokify** [comment]
@tylerlong Thanks for the update and explanation. `1.0.0-alpha1` is working for me now. Good investigation of ECB support too.
