### ISSUE TITLE
Setup AppVeyor for live tests.

### ISSUE THREAD

**Issue by tylerlong** [ringcentral/ringcentral-csharp#34]
`RingCentral.Test.Real` is the live unit test project, It looks for `config.json` file in current folder (`bin/Debug` or `bin/Release`). If it cannot find the file, all the live tests are ignored. Thus we cannot achieve our testing coverage goal (90+%).

We need to configure AppVeyor to provide such a file before testing is run. Could some one take a look? I lack the permission to do so because I am not the admin of this repository and I don't know whose AppVeyor account is in use.

@grokify

**Comment by grokify** [comment]
Some discussions:

**Securing Credentials**

Since GitHub and AppVeyor are public for this SDK, be sure to encrypt any sensitive information per the following:

* http://www.appveyor.com/docs/how-to/secure-files

Any accidental release of secure information should have that information invalidated and those files removed.

**Test Coverage**

Generally, target test coverage can be achieved using a combination of stubs / mocks, and limiting the code that is to be included for test coverage. That being said, it is nice to have live tests as well.

**AppVeyor Account**

AppVeyor accounts seem to be personal accounts and I'm not sure it would be possible to have a `ringcentral` account since that is a GitHub org and not a GitHub user. The current AppVeyor account being used is from @paulzolnierczyk who previously worked on the SDK. Please create a new one under your account. Once it is working, we can switch the link on the `README.md`

**Comment by tylerlong** [comment]
@grokify I still have a question: whenever we commit code, AppVeyor automatically runs testing. So how to tell GitHub which AppVeyor account to use? I don't think merely switching the link on the `README.md` does the trick.

**Comment by grokify** [comment]
@tylerlong AppVeyor is configured on the AppVeyor side. Do the following:

1. Sign into https://www.appveyor.com/
2. Under the menu link `PROJECTS` click the link for `(+) NEW PROJECT`
3. Under `Select Repository`, go to `GitHub` > `ringcentral` > `ringcentral-csharp`. Then click `(+) ADD` which will take you to a permalink like:

`https://ci.appveyor.com/project/YOUR_USERNAME/ringcentral-csharp`

Or 

`https://ci.appveyor.com/project/YOUR_USERNAME/ringcentral-csharp-SOME_UID`

AppVeyor has been configured to receive a webhook from GitHub whenever a new commit occurs.

**Comment by tylerlong** [comment]
@grokify since our project is open source, eveybody can configure it on AppVeyor. Let's say there 10 AppVeyor accounts which have this project. Question is: in PR page, such as https://github.com/ringcentral/ringcentral-csharp/pull/33, which AppVeyor account is used for the following report:

![screen shot 2016-05-29 at 10 40 36 am](https://cloud.githubusercontent.com/assets/733544/15631112/d4fd08de-2589-11e6-8ebb-41af7dbbd039.png)

**Comment by grokify** [comment]
@tylerlong I'm actually not sure how GitHub selects which one to use in that report. Do you know?

In general, I think we should have a primary AppVeyor account we use. Ideally this could be a `ringcentral` one but since AppVeyor is tied to user accounts, I was thinking we could perhaps use yours since you are the primary maintainer of the C# SDK now. What do you think?

**Comment by tylerlong** [comment]
It is OK to use my personal AppVeyor account. I will do more investigation about how GitHub selects AppVeyor account by creating a demo project which I have admin permission.

**Comment by grokify** [comment]
@tylerlong After doing a search, it seems like we can create an organization account on AppVeyor. This would still be tied to an email address but not linked to a GitHub account as described below:

* http://help.appveyor.com/discussions/questions/1154-appveyor-account-for-github-organizations

Take a look at creating a `ringcentral` organization account on AppVeyor so that the project URL will say `ringcentral`.

**Comment by tylerlong** [comment]
Different AppVeyor projects from different AppVeyor accounts have different webhook urls. Admin of GitHub project can configure the webhook to specify an AppVeyor project. This answers: " how GitHub selects which one to use in that report".

**Comment by tylerlong** [comment]
@grokify https://ci.appveyor.com/project/ringcentral/ringcentral-csharp I have created orginazation account `ringcentral`. Please check your Skype message to configure GitHub.

**Comment by tylerlong** [comment]
@grokify Could you please take some actions? Let's switch AppVeyor to company account.

**Comment by tylerlong** [comment]
I want to mark this as won't fix. Because this repository is quite stable now and we haven't added any new features since half a year ago. So it doesn't make much sense to test it further.

And by the way, we want to advertise https://github.com/ringcentral/ringcentral-csharp-client instead of this repository because it's simpler to use and users like it more.
