### ISSUE TITLE
0.0.36 SubscriptionServiceImplementation does not have 3 argument Subscribe method

### ISSUE THREAD

**Issue by grokify** [ringcentral/ringcentral-csharp#4]
When using version 0.0.36 from NuGet, I still get method signatures for 0 arguments and 5 arguments, not the 3 arguments that is in the latest code and README.md: commit d225e6e354a23ca332b82868314e2181198343c8.

Please update the NuGet package to include the 3 argument Subscribe method.

**Comment by nrobison** [comment]
Nuget has been updated to reflect these changes. Please update to version 0.0.37.

**Comment by grokify** [comment]
Version 0.0.37 takes three `Action<object>` callbacks now, however, the received `object` still appears to be an encrypted payload from Pubnub.

To get the decrypted object in the call back, it seems the type should be `Action<JObject>` with the result being the result of a decryption operation, such as the `public JObject DecryptMessage(object message)` method. To get the decrypted object back, does the method need to be changed to something like:

`public Response Subscribe(Action<JObject> userCallback, Action<JObject> connectCallback, Action<JObject> errorCallback)`

**Comment by nrobison** [comment]
You were correct about the decrypt issue. As of the current NuGet 0.0.39 decrypt occurs before calling any Callbacks passed into ```Subscribe()``` are passed the message. This was only an issue with Notification as the other messages ( Connect, Disconnect and Error) are not encrypted. 

I have updated the ReadMe to include new recipes for how to handle the messages returned. There was no change made to ```public Response Subscribe(Action<Object> userCallback, Action<Object> connectCallback, Action<Object> errorCallback)```. You are not required to process the object but the Callback must take the single Object parameter only. All messages returned from PubNub are based as a base Object. You can cast all of  the four messages (Notification, Connect, Disconnect and Error) to strings. Check the ReadMe for more examples but this shows how to cast it to JArray
```
public void ActionOnMessage(object message) {
	var ReceivedMessage = ((JArray)message).SelectToken("[0].body.changes[0].type");  
}
```
Or to a string
```
public void ActionOnMessage(object message) {
	var ReceivedMessage = message.ToString();  
}
```
**Only Notification and Connect are able to be cast to JArray**
This is due to the way errors and disconnects are returned from PubNub. Disconnect is actually a ```List<string>``` and error is a ```PubnubClientError``` from PubNub.LoggingMethod.

**Comment by grokify** [comment]
Thanks @nrobison. I have this working on .NET and Xamarin.iOS now.
