### ISSUE TITLE
Ignored test cases fails when running with Resharper test runner

### ISSUE THREAD

**Issue by dariusdamalakas** [ringcentral/ringcentral-csharp#45]
Hi,

This more of a query, not a blocker issue. [This code](https://github.com/ringcentral/ringcentral-csharp/blob/master/RingCentral.Test.Real/BaseTest.cs#L16) seems to ignore 9 tests cases
````
if (Config.Instance == null)
{
                Assert.Ignore();
}
````

This is ok in CI builds, but running these test with different test runners (Resharper, NCrunch) shows tests as failed.

Appveyour does not run 9 tests. Should those be removed then?
````
............................................................N.N.N.N.N.N.N.N.N 
Tests run: 59, Errors: 0, Failures: 0, Inconclusive: 0, Time: 3.605974 seconds
  Not run: 9, Invalid: 0, Ignored: 9, Skipped: 0
````

**Comment by tylerlong** [comment]
Ignored tests are all from [RingCentral.Test.Real](https://github.com/ringcentral/ringcentral-csharp/tree/master/RingCentral.Test.Real) project. It's called "real" because it is not "mocking".

You need to provide credentials configuration in order to run real tests. Please read the [readme file](https://github.com/ringcentral/ringcentral-csharp/blob/master/RingCentral.Test.Real/README.md) about how to run real tests.

I always run all of the tests on my dev machine. But AppVeyor only run the mocking tests. We would like to enable AppVeyor to run real tests too, but it's not prioritized. We have an issue to track it: https://github.com/ringcentral/ringcentral-csharp/issues/34

Since these test talks directly to API Server, I am not sure whether it's a good idea to run them automatically by some test runners such as ReSharper. Maybe we can find some way to disable them?

**Comment by tylerlong** [comment]
Close it for now because I've explained why and under what condition are those tests ignored. Feel free to reopen it if you have more questions.
