### ISSUE TITLE
Ringout Call issue in C#

### ISSUE THREAD

**Issue by CMCTest** [ringcentral/ringcentral-csharp#59]
I have tried the below request to make outbound calls using the SDK in c# and getting the below error.

An unhandled exception of type 'RingCentral.Http.ApiException' occurred in RingCentral.dll
Additional information: Parameter [to] value is invalid

Here is the sample request which i am posting,

sdk = new SDK("AppKey", "Secret Key", SDK.Server.Sandbox, "SubTest", "1.0.0");
sdk.Platform.Login("phone number", "", "password", true);

var ringoutPostBodyJson = "{\"from\":{\"phoneNumber\":\"19295755385\",\"to\":{\"phoneNumber\":\"15614097222\"},\"playPrompt\":true,\"country\":{\"id\":\"1\"}}";
var request = new Request("/restapi/v1.0/account/~/extension/~/ringout", ringoutPostBodyJson);
var ringoutResponse = sdk.Platform.Post(request);

**Comment by CMCTest** [comment]
i have fixed the issue, now i am able to send the request and get the response from the REST API.

However i am not receiving the outbound call to my phone? is there anything i need to pass to make the out bound call immediately.

**Comment by tylerlong** [comment]
You last comment is again not a C# question. I am not an expert but I will try my best to help you. 

In order to test outbound call, you need two phones. If the ringout is successful, both of the two phones will ring. And owners of these two phones can speak to each other.

If this doesn't help. Could you please post your question to http://stackoverflow.com/questions/tagged/ringcentral ? Then programmers from other programming languages(js, php, swift...etc) can benefit too.

**Comment by cobysolutions** [comment]
CMCTest, I am getting the same problem that you came across and fixed. What did you do to fix it?

**Comment by tylerlong** [comment]
I believe this issue has been resolved long ago. I have sent emails with sample code to the user. 

If it's not resolved or you still have concerns, feel free to create a new issue.
