### ISSUE TITLE
Unable to send text

### ISSUE THREAD

**Issue by khoughton-Landmark** [ringcentral/ringcentral-csharp#60]
Following the example tests, I am unable to send a test sms message.

`var sdk = new SDK(appKey, appSecret, apiServer, applicationName, applicationVersion);
sdk.Platform.Login(userName, extension, password, false);
var requestBody = new
{
    text = text,
    from = new { phoneNumber = fromPhoneNumber },
    to = new object[] { new { phoneNumber = toPhoneNumber } }
};

var jsonString = JsonConvert.SerializeObject(requestBody);
var request = new RingCentral.Http.Request("/restapi/v1.0/account/~/extension/~/sms", jsonString);
var response = sdk.Platform.Post(request);
`
The values used for each are:
appKey: wPHejJ32RZi6j3fQ154qTA
appSecret: _LC7r7LwQw22UKievgukvwGzvF8TsnSKynH8qDTQ-Qgw
apiServer: https://platform.devtest.ringcentral.com
applicationName: Landmark
applicationVersion: 1.1
userName: +16619640455
extension: 101
password: ****** (The correct password removed)
text: “Test”
from: 16616940455
to: 7145551212

**Comment by tylerlong** [comment]
Are there any errors or exceptions? Could you please post a screenshot together with the full stack trace?

**Comment by khoughton-Landmark** [comment]
Exception Message:
Parameter [from] value [16616940455] is invalid [Cannot find the phone number which belongs to user]


   at RingCentral.Http.ApiResponse..ctor(HttpResponseMessage response, HttpRequestMessage request)
   at RingCentral.Platform.Send(HttpMethod httpMethod, Request request)
   at RingCentral.Platform.Post(Request request)
   at Lmd.Utils.RingCentralWrapper.SendTextMessage(String toPhoneNumber, String fromPhoneNumber, String text) in D:\!code\Sprint\KH\Lmd.Utils\RingCentralWrapper.cs:line 99

The response object has a LOT of information in it.  If you’ll be more specific about what you’re looking for, I can give you better data.

Here’s a link to a screen shot of some of the data: http://screencast.com/t/K9QFSXxDZOCq

**Comment by tylerlong** [comment]
@khoughton-Landmark the error message says `Parameter [from] value [16616940455] is invalid [Cannot find the phone number which belongs to user]` and that's the root cause.

It means the number doesn't belong to the user you authorized. You can't send message on behalf of others (numbers).

It's not an issue about the sdk. It's an issue about the platform api. It's not the right place to ask such questions. Please post your question to http://stackoverflow.com/questions/tagged/ringcentral or https://devcommunity.ringcentral.com/ if the information above does not solve it.

**Comment by khoughton-Landmark** [comment]
Two numbers in the From address were transposed. Fixing that has resolved my issue.
