### ISSUE TITLE
SetData doesn't update the Authorization header

### ISSUE THREAD

**Issue by alexgritton** [ringcentral/ringcentral-csharp#64]
I'm not sure if this is by design but I think there should be an option to reset the Authorization header when setting the Auth data. If I load up the application and already have a valid auth token I want to set the Auth data and begin. Currently if I set the Auth data and try to Post I receive an error saying the Authorization header has not been set. I've looked through the source code and confirmed that it's not being set as well.

**Comment by tylerlong** [comment]
Confirmed. I am not sure it's by design or not, but you also need to invoke this line as well: https://github.com/ringcentral/ringcentral-csharp/blob/master/RingCentral/Platform/Platform.cs#L73

And by the way now have a new project: https://github.com/ringcentral/ringcentral-csharp-client it's more user friendly.

**Comment by alexgritton** [comment]
The new project is very nice. I'll switch over to that one today. Thanks for your help!
