### ISSUE TITLE
Help Requested - Get Message Store 

### ISSUE THREAD

**Issue by jmol123** [ringcentral/ringcentral-csharp#65]
When I run this code in an attempt to Get Message Store, the only thing that shows up in the command line is "RingCentral.Http.ApiResponse"

Would you be able to tell me how to pull the actual contents of the message store?

Thanks!!
- Julian

```csharp
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using RingCentral;
using RingCentral.Http;
using Newtonsoft.Json;

namespace ConsoleApplication1
{
    class Program
    {
        static void Main(string[] args)
        {
            var sdk = new SDK(
                "",
                "",
                SDK.Server.Sandbox,
                "",
                "1.0.0");
            // Password Grant Authorization
            sdk.Platform.Login(", "101", "", true);

            var request = new Request("/restapi/v1.0/account/~/extension/~/message-store");
            var response = sdk.Platform.Get(request);
            Console.WriteLine(response.ToString());
            Console.ReadLine();
        }
    }
}
```

**Comment by tylerlong** [comment]
You can set a breakpoint on the `response` line and inspect its properties. I remember it has a property named `Json` which is a JSON.net object. 

You need to parse the json response like below: https://github.com/ringcentral/ringcentral-csharp/blob/master/RingCentral.Test.Real/AddressBookTest.cs#L31

I would recommend https://github.com/ringcentral/ringcentral-csharp-client because it's way simpler to use:

https://github.com/ringcentral/ringcentral-csharp-client/blob/master/RingCentral.Test/BinaryTest.cs#L51

**Comment by jmol123** [comment]
Tyler is 100% correct that the Client is much simpler to use.  I will close this out, as I have migrated my environment over to the Client.  Thanks again Tyler!!
