### ISSUE TITLE
Question: Can I use this with a white-labelled RingCentral account?

### ISSUE THREAD

**Issue by kidmeke** [ringcentral/ringcentral-csharp#66]
Hi,

We are using a white-labelled version of RingCentral (Telus BusinessConnect) and have written some code that uses the RingCentral API. We have been testing with a RingCentral dev account which of course works fine and want to test with an actual account now.

Are there any obstacles to using the SDK with an affiliate account like Telus BusinessConnect? Since the server urls are hard-coded in the SDK, I'm wondering if we'll run into problems in the scenario I've outlined.

Thanks

**Comment by tylerlong** [comment]
I have no experience with that and I've also never heard of such issues.

> Since the server urls are hard-coded in the SDK

User can also specify different sever url.

I think it should just work. Let me know if it doesn't work for you.

**Comment by LingForCC** [comment]
@kidmeke  Since RingCentral provides unified Platform API for different types of accounts, the SDK should be suitable for your case. I don't think you will have any problem. But one thing to notice is that your App key/secret needs to support TELUS brand. You can contact with devsupport@ringcentral.com and ask them to add corresponding configuration.
